--liquibase formatted sql

--changeset ilya:1


CREATE TABLE to_do_data (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_task VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);
